zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    order-service:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true

hystrix:
  command:
    order-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 20000

order-service:
  ribbon:
    eureka:
      enabled: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      perferIpAddress: true

server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
